export enum ConversationState {
  IDLE = 'IDLE',
  WAITING_AMOUNT = 'WAITING_AMOUNT',
  WAITING_PROVIDER = 'WAITING_PROVIDER',
  WAITING_CATEGORY = 'WAITING_CATEGORY',
  WAITING_DESCRIPTION = 'WAITING_DESCRIPTION',
  WAITING_RECEIPT = 'WAITING_RECEIPT',
  WAITING_CONFIRMATION = 'WAITING_CONFIRMATION',
  EDITING_FIELD = 'EDITING_FIELD',
}
